[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm ci --include=dev"]

[phases.build]
cmds = ["cd backend && npm run build"]

[variables]
NODE_ENV = "production"
